### ISSUE TITLE
which network variant has better performance?

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/OverthINKingSegmenter#1]
hi @hammb ,

thanks for sharing the awesome work!

i have two quick questions:

1. what is the motivation to use the 3D Encoder 2D Decoder U-Net model with SE blocks?

2. which network variant has better performance?

https://github.com/MIC-DKFZ/OverthINKingSegmenter/tree/master/nnunetv2/training/nnUNetTrainer/variants/network_architecture

**Comment by hammb** [comment]
Hi :)

This was our work during the Vesuvius Ink Detection Challenge. We tried lots of different configurations (including normal 2D-UNet and 3D-UNet) but the 3D Encoder 2D Decoder UNet with SE blocks just performed best for the challange task due to the 3D on 2D nature of the problem. So the answer to 2.) is the motivation for 1.)
